AMPG = read.csv(file = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data", sep = "", header = FALSE)
AMPG = AMPG[,-9]
names(AMPG) = c("mpg","cylinders","displacement","horsepower","weight","acceleration","model year","origin")
AMPG = AMPG[!AMPG$horsepower=="?",]
AMPG$horsepower = as.numeric(as.character(AMPG$horsepower))
summary(AMPG)
plot(AMPG)
MPG_model=lm(mpg~. , AMPG)
summary(MPG_model)
MPG_model1=update(MPG_model,.~.-acceleration)
summary(MPG_model1)
MPG_model2=update(MPG_model1,.~.-cylinders)
summary(MPG_model2)
sum(resid(MPG_model)^2)
sum(resid(MPG_model1)^2)
sum(resid(MPG_model2)^2)
anova(MPG_model,MPG_model1)
anova(MPG_model,MPG_model2)

wine.red = read.csv(file = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", header = TRUE, sep = ";")
summary(wine.red)
pr.wine.red = prcomp(wine.red, scale=TRUE)
pr.wine.red
biplot(pr.wine.red,scale = 0,expand =2.4,xlim=c(-12,12), ylim=c(-12,8))
wine.pc12.red = data.frame(pr.wine.red$x[,1],pr.wine.red$x[,2])
plot(wine.pc12.red, main = "Clustering on PC1 and PC2", xlab="PC1", ylab="PC2")
km.wine.pc12.red = kmeans(wine.pc12.red, centers = 7)
plot(wine.pc12.red ,col = km.wine.pc12.red$cluster,main = "Clustering on PC1 and PC2", xlab="PC1", ylab="PC2")

wine.white = read.csv(file = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", header = TRUE, sep = ";")
summary(wine.white)
pr.wine.white = prcomp(wine.white, scale=TRUE)
pr.wine.white
biplot(pr.wine.white,scale = 0,expand=2,xlim=c(-12,10),ylim=c(-12,12))
summary(pr.wine.white)
wine.pc12 = data.frame(pr.wine.white$x[,1],pr.wine.white$x[,2])
plot(wine.pc12,main = "Clustering on PC1 and PC2", xlab="PC1", ylab="PC2",pch=20,cex=0.3)
km.wine.pc12 = kmeans(wine.pc12, centers = 7)
plot(wine.pc12,col = km.wine.pc12$cluster,main = "Clustering on PC1 and PC2", xlab="PC1", ylab="PC2",cex=0.3, pch=20)